=== alshund/task-3.3-Shundrik/src/main/resources/xml/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http:://www.web.tr.com/student"
        xmlns:sns="http:://www.web.tr.com/student"
        xmlns:pns="http://www.web.tr.com/parent">

    <element name="students">
        <complexType>
            <sequence>
                <element name="student" type="sns:Student" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    
    <complexType name="Student">
        <sequence>
            <element name="surname" type="string"/>
            <element name="first_name" type="string"/>
            <element name="patronymic" type="string"/>
            <element name="father" type="pns:Parent" minOccurs="1" maxOccurs="1"/>
            <element name="mother" type="pns:Parent" minOccurs="1" maxOccurs="1"/>
            <element name="brothers_amount" type="int"/>
            <element name="sisters_amount" type="int"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>


</schema>

=== alshund/task-3.3-Shundrik/src/main/resources/Students.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<sns:students xmlns:sns="http:://www.web.tr.com/student"
              xmlns:fns="http://www.web.tr.com/parent"
              xmlns:mns="http://www.web.tr.com/parent"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http:://www.web.tr.com/student Students.xsd">
    <student>
        <surname>Князев</surname>
        <first_name>Рудольф</first_name>
        <patronymic>Ильич</patronymic>
        <father>
            <fns:surname>Ермаков</fns:surname>
            <fns:first_name>Дмитрий</fns:first_name>
            <fns:patronymic>Ростиславович</fns:patronymic>
            <fns:salary>6151.91</fns:salary>
        </father>
        <mother>
            <mns:surname>Мышкин</mns:surname>
            <mns:first_name>Весна</mns:first_name>
            <mns:patronymic>Викторовна</mns:patronymic>
            <mns:salary>6277.1</mns:salary>
        </mother>
        <brothers_amount>16</brothers_amount>
        <sisters_amount>12</sisters_amount>
    </student>
    <student>
        <surname>Некрасов</surname>
        <first_name>Виталий</first_name>
        <patronymic>Миронович</patronymic>
        <father>
            <fns:surname>Доронин</fns:surname>
            <fns:first_name>Даниил</fns:first_name>
            <fns:patronymic>Валентинович</fns:patronymic>
            <fns:salary>9458.47</fns:salary>
        </father>
        <mother>
            <mns:surname>Мышкин</mns:surname>
            <mns:first_name>Злата</mns:first_name>
            <mns:patronymic>Семеновна</mns:patronymic>
            <mns:salary>1637.3</mns:salary>
        </mother>
        <brothers_amount>6</brothers_amount>
        <sisters_amount>5</sisters_amount>
    </student>
    <student>
        <surname>Евдокимов</surname>
        <first_name>Вили</first_name>
        <patronymic>Максович</patronymic>
        <father>
            <fns:surname>Иванков</fns:surname>
            <fns:first_name>Тимур</fns:first_name>
            <fns:patronymic>Вячеславович</fns:patronymic>
            <fns:salary>3729.97</fns:salary>
        </father>
        <mother>
            <mns:surname>Осипов</mns:surname>
            <mns:first_name>Борислава</mns:first_name>
            <mns:patronymic>Матвеевна</mns:patronymic>
            <mns:salary>1840.4</mns:salary>
        </mother>
        <brothers_amount>1</brothers_amount>
        <sisters_amount>20</sisters_amount>
    </student>
    <student>
        <surname>Носков</surname>
        <first_name>Аристарх</first_name>
        <patronymic>Рудольфович</patronymic>
        <father>
            <fns:surname>Герасимов</fns:surname>
            <fns:first_name>Вадим</fns:first_name>
            <fns:patronymic>Евгеньевич</fns:patronymic>
            <fns:salary>9020.83</fns:salary>
        </father>
        <mother>
            <mns:surname>Яковлев</mns:surname>
            <mns:first_name>Малуша</mns:first_name>
            <mns:patronymic>Петровна</mns:patronymic>
            <mns:salary>6046.0</mns:salary>
        </mother>
        <brothers_amount>6</brothers_amount>
        <sisters_amount>9</sisters_amount>
    </student>
    <student>
        <surname>Хохлов</surname>
        <first_name>Карл</first_name>
        <patronymic>Игоревич</patronymic>
        <father>
            <fns:surname>Наумов</fns:surname>
            <fns:first_name>Борис</fns:first_name>
            <fns:patronymic>Филиппович</fns:patronymic>
            <fns:salary>1270.66</fns:salary>
        </father>
        <mother>
            <mns:surname>Гаврилов</mns:surname>
            <mns:first_name>Доля</mns:first_name>
            <mns:patronymic>Дмитриевна</mns:patronymic>
            <mns:salary>7148.2</mns:salary>
        </mother>
        <brothers_amount>20</brothers_amount>
        <sisters_amount>20</sisters_amount>
    </student>
</sns:students>
